# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modify_nickname.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'modify_nickname.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15modify_nickname.proto\"9\n\x11ModifyNicknameReq\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\x03\"K\n\x11ModifyNicknameRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cnew_nickname\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modify_nickname_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODIFYNICKNAMEREQ']._serialized_start=25
  _globals['_MODIFYNICKNAMEREQ']._serialized_end=82
  _globals['_MODIFYNICKNAMERES']._serialized_start=84
  _globals['_MODIFYNICKNAMERES']._serialized_end=159
# @@protoc_insertion_point(module_scope)
